// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://cbpqnomvmpsjzxbrtxed.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNicHFub212bXBzanp4YnJ0eGVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA1MjA0OTMsImV4cCI6MjA5NjA5NjQ5M30.AkSs8DUSHnO6kqEzM_3RZpFWiMKitGZr-w6kdUrmjfQ";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);